<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $districts = [
            ['id' => '103','province_id' => '1','name_en' => 'CHAHAR ASYAB','name_dr' => 'چهارآسیاب','name_pa' => 'چهارآسیاب'],
            ['id' => '104','province_id' => '1','name_en' => 'BAGRAMI','name_dr' => 'بگرامی','name_pa' => 'بگرامی'],
            ['id' => '105','province_id' => '1','name_en' => 'DEHSABZ','name_dr' => 'ده سبز','name_pa' => 'ده سبز'],
            ['id' => '106','province_id' => '1','name_en' => 'SHAKAR DARA','name_dr' => 'شکردره','name_pa' => 'شکردره'],
            ['id' => '107','province_id' => '1','name_en' => 'MUSAHI','name_dr' => 'موسئی','name_pa' => 'موسئی'],
            ['id' => '108','province_id' => '1','name_en' => 'MIR BACHA KOT','name_dr' => 'میر بچه کوت','name_pa' => 'میر بچه کوت'],
            ['id' => '109','province_id' => '1','name_en' => 'KHAK-E-JABAR','name_dr' => 'خاک جبار','name_pa' => 'خاک جبار'],
            ['id' => '110','province_id' => '1','name_en' => 'KALAKAN','name_dr' => 'کلکان','name_pa' => 'کلکان'],
            ['id' => '111','province_id' => '1','name_en' => 'GULDARA','name_dr' => 'گلدره','name_pa' => 'گلدره'],
            ['id' => '112','province_id' => '1','name_en' => 'FARZA','name_dr' => 'فرزه','name_pa' => 'فرزه'],
            ['id' => '113','province_id' => '1','name_en' => 'ESTALEF','name_dr' => 'استالف','name_pa' => 'استالف'],
            ['id' => '114','province_id' => '1','name_en' => 'QARA BAGH','name_dr' => 'قره باغ','name_pa' => 'قره باغ'],
            ['id' => '115','province_id' => '1','name_en' => 'SURUBI','name_dr' => 'سروبی','name_pa' => 'سروبی'],
            ['id' => '116','province_id' => '1','name_en' => 'PD1','name_dr' => 'ناحیه1','name_pa' => 'ناحیه1'],
            ['id' => '117','province_id' => '1','name_en' => 'PD2','name_dr' => 'ناحیه2','name_pa' => 'ناحیه2'],
            ['id' => '118','province_id' => '1','name_en' => 'PD3','name_dr' => 'ناحیه3','name_pa' => 'ناحیه3'],
            ['id' => '119','province_id' => '1','name_en' => 'PD 4','name_dr' => 'ناحیه 4','name_pa' => 'ناحیه 4'],
            ['id' => '120','province_id' => '1','name_en' => 'PD 5','name_dr' => 'ناحیه 5','name_pa' => 'ناحیه 5'],
            ['id' => '121','province_id' => '1','name_en' => 'PD 6 ','name_dr' => 'ناحیه 6 ','name_pa' => 'ناحیه 6 '],
            ['id' => '122','province_id' => '1','name_en' => 'PD 7 ','name_dr' => 'ناحیه 7 ','name_pa' => 'ناحیه 7 '],
            ['id' => '123','province_id' => '1','name_en' => 'PD 8 ','name_dr' => 'ناحیه 8 ','name_pa' => 'ناحیه 8 '],
            ['id' => '124','province_id' => '1','name_en' => 'PD 9 ','name_dr' => 'ناحیه 9 ','name_pa' => 'ناحیه 9 '],
            ['id' => '125','province_id' => '1','name_en' => 'PD 10 ','name_dr' => 'ناحیه 10 ','name_pa' => 'ناحیه 10 '],
            ['id' => '126','province_id' => '1','name_en' => 'PD 11 ','name_dr' => 'ناحیه 11 ','name_pa' => 'ناحیه 11 '],
            ['id' => '127','province_id' => '1','name_en' => 'PD 12 ','name_dr' => 'ناحیه 12 ','name_pa' => 'ناحیه 12 '],
            ['id' => '128','province_id' => '1','name_en' => 'PD 13 ','name_dr' => 'ناحیه 13 ','name_pa' => 'ناحیه 13 '],
            ['id' => '129','province_id' => '1','name_en' => 'PD 14 ','name_dr' => 'ناحیه 14 ','name_pa' => 'ناحیه 14 '],
            ['id' => '130','province_id' => '1','name_en' => 'PD 15 ','name_dr' => 'ناحیه 15 ','name_pa' => 'ناحیه 15 '],
            ['id' => '131','province_id' => '1','name_en' => 'PD 16 ','name_dr' => 'ناحیه 16 ','name_pa' => 'ناحیه 16 '],
            ['id' => '132','province_id' => '1','name_en' => 'PD 17 ','name_dr' => 'ناحیه 17 ','name_pa' => 'ناحیه 17 '],
            ['id' => '133','province_id' => '1','name_en' => 'PD 18 ','name_dr' => 'ناحیه 18 ','name_pa' => 'ناحیه 18 '],
            ['id' => '134','province_id' => '1','name_en' => 'PD 19 ','name_dr' => 'ناحیه 19 ','name_pa' => 'ناحیه 19 '],
            ['id' => '135','province_id' => '1','name_en' => 'PD 20 ','name_dr' => 'ناحیه 20 ','name_pa' => 'ناحیه 20 '],
            ['id' => '136','province_id' => '1','name_en' => 'PD 21 ','name_dr' => 'ناحیه 21 ','name_pa' => 'ناحیه 21 '],
            ['id' => '137','province_id' => '1','name_en' => 'PD 22 ','name_dr' => 'ناحیه 22 ','name_pa' => 'ناحیه 22 '],
            ['id' => '138','province_id' => '1','name_en' => 'Unknown ','name_dr' => 'نامعلوم ','name_pa' => 'نامعلوم '],
            ['id' => '139','province_id' => '1','name_en' => 'Paghman','name_dr' => 'پغمان','name_pa' => 'پغمان'],
            ['id' => '201','province_id' => '2','name_en' => 'PROVINCIAL CAPITAL OF KAPISA (MAHMUDI RAQI)','name_dr' => '( مرکز ولایت کاپیسا) محمود راقی','name_pa' => '( مرکز ولایت کاپیسا) محمود راقی'],
            ['id' => '202','province_id' => '2','name_en' => 'HISSA-E- DUWUMI KOHISTAN','name_dr' => 'حصه دوم کوهستان','name_pa' => 'حصه دوم کوهستان'],
            ['id' => '203','province_id' => '2','name_en' => 'KOH BAND','name_dr' => 'کوه بند','name_pa' => 'کوه بند'],
            ['id' => '204','province_id' => '2','name_en' => 'HISSA-E-AWALI KOHISTAN','name_dr' => 'حصه اول کوهستان','name_pa' => 'حصه اول کوهستان'],
            ['id' => '205','province_id' => '2','name_en' => 'NIJRAB','name_dr' => 'نجراب','name_pa' => 'نجراب'],
            ['id' => '206','province_id' => '2','name_en' => 'TAGAB','name_dr' => 'تگاب','name_pa' => 'تگاب'],
            ['id' => '207','province_id' => '2','name_en' => 'ALASAY','name_dr' => 'اله سای','name_pa' => 'اله سای'],
            ['id' => '208','province_id' => '2','name_en' => 'Unknown','name_dr' => 'نا معلوم','name_pa' => 'نا معلوم'],
            ['id' => '209','province_id' => '2','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '210','province_id' => '2','name_en' => 'PD 2','name_dr' => 'ناحیه 2','name_pa' => 'ناحیه 2'],
            ['id' => '301','province_id' => '3','name_en' => 'PROVINCIAL CAPITAL OF PARWAN (CHARIKAR)','name_dr' => '( مرکز ولایت پروان) چاریکار','name_pa' => '( مرکز ولایت پروان) چاریکار'],
            ['id' => '302','province_id' => '3','name_en' => 'BAGRAM','name_dr' => 'بگرام','name_pa' => 'بگرام'],
            ['id' => '303','province_id' => '3','name_en' => 'SHINWARI','name_dr' => 'شینواری','name_pa' => 'شینواری'],
            ['id' => '304','province_id' => '3','name_en' => 'SAYID KHALE','name_dr' => 'سید خیل','name_pa' => 'سید خیل'],
            ['id' => '305','province_id' => '3','name_en' => 'JABULUSSARAJ','name_dr' => 'جبل السراج','name_pa' => 'جبل السراج'],
            ['id' => '306','province_id' => '3','name_en' => 'SALANG','name_dr' => 'سالنگ','name_pa' => 'سالنگ'],
            ['id' => '307','province_id' => '3','name_en' => 'SYAHGIRDI GHORBAND','name_dr' => 'سیاه گرد غوربند','name_pa' => 'سیاه گرد غوربند'],
            ['id' => '308','province_id' => '3','name_en' => 'KOHI SAFI','name_dr' => 'کوه صافی','name_pa' => 'کوه صافی'],
            ['id' => '309','province_id' => '3','name_en' => 'SORKHI PARSA','name_dr' => 'سرخ پارسا','name_pa' => 'سرخ پارسا'],
            ['id' => '310','province_id' => '3','name_en' => 'SHAYKH ALI','name_dr' => 'شیخ علی','name_pa' => 'شیخ علی'],
            ['id' => '312','province_id' => '3','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '313','province_id' => '3','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '314','province_id' => '3','name_en' => 'PD 2','name_dr' => 'ناحیه 2','name_pa' => 'ناحیه 2'],
            ['id' => '315','province_id' => '3','name_en' => 'PD 3','name_dr' => 'ناحیه 3','name_pa' => 'ناحیه 3'],
            ['id' => '316','province_id' => '3','name_en' => 'PD 4','name_dr' => 'ناحیه 4','name_pa' => 'ناحیه 4'],
            ['id' => '317','province_id' => '3','name_en' => 'PD 5','name_dr' => 'ناحیه 5','name_pa' => 'ناحیه 5'],
            ['id' => '318','province_id' => '3','name_en' => 'PD 6','name_dr' => 'ناحیه 6','name_pa' => 'ناحیه 6'],
            ['id' => '319','province_id' => '3','name_en' => 'PD 7','name_dr' => 'ناحیه 7','name_pa' => 'ناحیه 7'],
            ['id' => '401','province_id' => '4','name_en' => 'PROVINCIAL CAPITAL OF WARDAK (MAYDAN SHAHR)','name_dr' => '( مرکز ولایت وردک) میدان شهر','name_pa' => '( مرکز ولایت وردک) میدان شهر'],
            ['id' => '402','province_id' => '4','name_en' => 'NERKH','name_dr' => 'نرخ','name_pa' => 'نرخ'],
            ['id' => '403','province_id' => '4','name_en' => 'JALREZ','name_dr' => 'جلریز','name_pa' => 'جلریز'],
            ['id' => '404','province_id' => '4','name_en' => 'CHAKI WARDAK','name_dr' => 'چک وردک','name_pa' => 'چک وردک'],
            ['id' => '405','province_id' => '4','name_en' => 'SAYYDABAD','name_dr' => 'سید آباد','name_pa' => 'سید آباد'],
            ['id' => '406','province_id' => '4','name_en' => 'DAYMIRDAD','name_dr' => 'دایمیرداد','name_pa' => 'دایمیرداد'],
            ['id' => '407','province_id' => '4','name_en' => 'HISSA-E-AWALI BIHSUD','name_dr' => 'حصه اول بهسود','name_pa' => 'حصه اول بهسود'],
            ['id' => '408','province_id' => '4','name_en' => 'JAGHATU','name_dr' => 'جغتو','name_pa' => 'جغتو'],
            ['id' => '409','province_id' => '4','name_en' => 'MARKAZ-E-BEHSUD','name_dr' => 'مرکز بهسود','name_pa' => 'مرکز بهسود'],
            ['id' => '410','province_id' => '4','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '501','province_id' => '5','name_en' => '(PROVINCIAL CAPITAL OF  LOGAR) PULI ALAM','name_dr' => '(مرکز ولایت لوگر) پل علم','name_pa' => '(مرکز ولایت لوگر) پل علم'],
            ['id' => '502','province_id' => '5','name_en' => 'BARAKI BARAK','name_dr' => 'برکی برک','name_pa' => 'برکی برک'],
            ['id' => '503','province_id' => '5','name_en' => 'CHARKH','name_dr' => 'چرخ','name_pa' => 'چرخ'],
            ['id' => '504','province_id' => '5','name_en' => 'KHUSHI','name_dr' => 'خوشی','name_pa' => 'خوشی'],
            ['id' => '505','province_id' => '5','name_en' => 'MOHAMMAD AGHA','name_dr' => 'محمد آغه','name_pa' => 'محمد آغه'],
            ['id' => '506','province_id' => '5','name_en' => 'KHAR WAR','name_dr' => 'خروار','name_pa' => 'خروار'],
            ['id' => '507','province_id' => '5','name_en' => 'AZRA','name_dr' => 'ازره','name_pa' => 'ازره'],
            ['id' => '508','province_id' => '5','name_en' => 'Unknown','name_dr' => 'نا معلوم','name_pa' => 'نا معلوم'],
            ['id' => '602','province_id' => '6','name_en' => 'BEHSUD','name_dr' => 'بهسود','name_pa' => 'بهسود'],
            ['id' => '603','province_id' => '6','name_en' => 'SORKH RUD','name_dr' => 'سرخرود','name_pa' => 'سرخرود'],
            ['id' => '604','province_id' => '6','name_en' => 'CHAPARHAR','name_dr' => 'چپرهار','name_pa' => 'چپرهار'],
            ['id' => '605','province_id' => '6','name_en' => 'KAMA','name_dr' => 'کامه','name_pa' => 'کامه'],
            ['id' => '606','province_id' => '6','name_en' => 'KUZKUNAR','name_dr' => 'کوزکنر','name_pa' => 'کوزکنر'],
            ['id' => '607','province_id' => '6','name_en' => 'RODAT','name_dr' => 'رودات','name_pa' => 'رودات'],
            ['id' => '608','province_id' => '6','name_en' => 'KHUGYANI','name_dr' => 'خوگیانی','name_pa' => 'خوگیانی'],
            ['id' => '609','province_id' => '6','name_en' => 'BATI KOT','name_dr' => 'بتی کوت','name_pa' => 'بتی کوت'],
            ['id' => '610','province_id' => '6','name_en' => 'DEH BALA','name_dr' => 'ده بالا','name_pa' => 'ده بالا'],
            ['id' => '611','province_id' => '6','name_en' => 'PACHIR WAGAM','name_dr' => 'پچیرواگام','name_pa' => 'پچیرواگام'],
            ['id' => '612','province_id' => '6','name_en' => 'DARAH-E-NOOR','name_dr' => 'دره نور','name_pa' => 'دره نور'],
            ['id' => '613','province_id' => '6','name_en' => 'KOT','name_dr' => 'کوت','name_pa' => 'کوت'],
            ['id' => '614','province_id' => '6','name_en' => 'GOSHTA','name_dr' => 'گوشته','name_pa' => 'گوشته'],
            ['id' => '615','province_id' => '6','name_en' => 'ACHIN','name_dr' => 'اچین','name_pa' => 'اچین'],
            ['id' => '616','province_id' => '6','name_en' => 'SHINWAR','name_dr' => 'شینوار','name_pa' => 'شینوار'],
            ['id' => '617','province_id' => '6','name_en' => 'MUHMAND DARA','name_dr' => 'مهمنددره','name_pa' => 'مهمنددره'],
            ['id' => '618','province_id' => '6','name_en' => 'LALPOOR','name_dr' => 'لعل پور','name_pa' => 'لعل پور'],
            ['id' => '619','province_id' => '6','name_en' => 'SHER ZAD','name_dr' => 'شیرزاد','name_pa' => 'شیرزاد'],
            ['id' => '620','province_id' => '6','name_en' => 'NAZYAN','name_dr' => 'نازیان','name_pa' => 'نازیان'],
            ['id' => '621','province_id' => '6','name_en' => 'HESARAK','name_dr' => 'حصارک','name_pa' => 'حصارک'],
            ['id' => '622','province_id' => '6','name_en' => 'DUR BABA','name_dr' => 'دربابا','name_pa' => 'دربابا'],
            ['id' => '623','province_id' => '6','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '624','province_id' => '6','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '625','province_id' => '6','name_en' => 'PD 2','name_dr' => 'ناحیه 2','name_pa' => 'ناحیه 2'],
            ['id' => '626','province_id' => '6','name_en' => 'PD 3','name_dr' => 'ناحیه 3','name_pa' => 'ناحیه 3'],
            ['id' => '627','province_id' => '6','name_en' => 'PD 4','name_dr' => 'ناحیه 4','name_pa' => 'ناحیه 4'],
            ['id' => '628','province_id' => '6','name_en' => 'PD 5','name_dr' => 'ناحیه 5','name_pa' => 'ناحیه 5'],
            ['id' => '629','province_id' => '6','name_en' => 'Provincial Capital of Nangarhar) Jalalabad)','name_dr' => '(مرکز لایت ننگرهار) جلال آباد','name_pa' => '(مرکز لایت ننگرهار) جلال آباد'],
            ['id' => '630','province_id' => '6','name_en' => 'SPENGHAR','name_dr' => 'اسپین غر ','name_pa' => 'اسپین غر '],
            ['id' => '701','province_id' => '7','name_en' => '(PROVINCIAL CAPITAL OF  LAGHMAN) MEHTERLAM','name_dr' => '( مرکز ولایت لغمان) مهترلام','name_pa' => '( مرکز ولایت لغمان) مهترلام'],
            ['id' => '702','province_id' => '7','name_en' => 'QARGHAYEE','name_dr' => 'قرغیی','name_pa' => 'قرغیی'],
            ['id' => '703','province_id' => '7','name_en' => 'ALISHING','name_dr' => 'علیشنگ','name_pa' => 'علیشنگ'],
            ['id' => '704','province_id' => '7','name_en' => 'ALINGAR','name_dr' => 'علینگار','name_pa' => 'علینگار'],
            ['id' => '705','province_id' => '7','name_en' => 'DAWLAT SHAH','name_dr' => 'دولت شاه','name_pa' => 'دولت شاه'],
            ['id' => '706','province_id' => '7','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '707','province_id' => '7','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '708','province_id' => '7','name_en' => 'PD 2','name_dr' => 'ناحیه 2','name_pa' => 'ناحیه 2'],
            ['id' => '801','province_id' => '8','name_en' => 'PROVINCIAL CAPITAL OF  PANJSHER ( BAZARAK )','name_dr' => '( مرکز ولایت پنجشیر) بازارک','name_pa' => '( مرکز ولایت پنجشیر) بازارک'],
            ['id' => '802','province_id' => '8','name_en' => 'RUKHA','name_dr' => 'رخه','name_pa' => 'رخه'],
            ['id' => '803','province_id' => '8','name_en' => 'DARAH','name_dr' => 'دره','name_pa' => 'دره'],
            ['id' => '804','province_id' => '8','name_en' => 'HISSA-E-AWAL ( KHINJ )','name_dr' => 'حصه اول - خنج','name_pa' => 'حصه اول - خنج'],
            ['id' => '805','province_id' => '8','name_en' => 'UNABA','name_dr' => 'عنابه','name_pa' => 'عنابه'],
            ['id' => '806','province_id' => '8','name_en' => 'SHUTUL','name_dr' => 'شتل','name_pa' => 'شتل'],
            ['id' => '807','province_id' => '8','name_en' => 'PARYAN','name_dr' => 'پریان','name_pa' => 'پریان'],
            ['id' => '808','province_id' => '8','name_en' => 'Unknown','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '901','province_id' => '9','name_en' => 'PROVINCIAL CAPITAL OF BAGHLAN ( PUL-E-KHUMRI )','name_dr' => '( مرکز ولایت بغلان) پلخمری','name_pa' => '( مرکز ولایت بغلان) پلخمری'],
            ['id' => '902','province_id' => '9','name_en' => 'DAHANA-E-GHURI','name_dr' => 'دهنه غوری','name_pa' => 'دهنه غوری'],
            ['id' => '903','province_id' => '9','name_en' => 'DUSHI','name_dr' => 'دوشی','name_pa' => 'دوشی'],
            ['id' => '904','province_id' => '9','name_en' => 'NAHREEN','name_dr' => 'نهرین','name_pa' => 'نهرین'],
            ['id' => '905','province_id' => '9','name_en' => 'BAGHLAN-E-JADEED','name_dr' => 'بغلان جید','name_pa' => 'بغلان جید'],
            ['id' => '906','province_id' => '9','name_en' => 'KHINJAN','name_dr' => 'خنجان','name_pa' => 'خنجان'],
            ['id' => '907','province_id' => '9','name_en' => 'ANDARAB','name_dr' => 'اندراب','name_pa' => 'اندراب'],
            ['id' => '908','province_id' => '9','name_en' => 'DEH SALAH','name_dr' => 'ده صلاح','name_pa' => 'ده صلاح'],
            ['id' => '909','province_id' => '9','name_en' => 'JALGA','name_dr' => 'جلگه','name_pa' => 'جلگه'],
            ['id' => '910','province_id' => '9','name_en' => 'BURKA','name_dr' => 'برکه','name_pa' => 'برکه'],
            ['id' => '911','province_id' => '9','name_en' => 'TALA WA BARFAK','name_dr' => 'تاله وبرفک','name_pa' => 'تاله وبرفک'],
            ['id' => '912','province_id' => '9','name_en' => 'PUL-E-HISAR','name_dr' => 'پل حصار','name_pa' => 'پل حصار'],
            ['id' => '913','province_id' => '9','name_en' => 'KHOST WA FIRING','name_dr' => 'خوست و فرنگ','name_pa' => 'خوست و فرنگ'],
            ['id' => '914','province_id' => '9','name_en' => 'GOZARGAH-E-NOOR','name_dr' => 'گذرگاه نور','name_pa' => 'گذرگاه نور'],
            ['id' => '915','province_id' => '9','name_en' => 'FIRING WA GHARU','name_dr' => 'فرنگ وغارو','name_pa' => 'فرنگ وغارو'],
            ['id' => '916','province_id' => '9','name_en' => 'PD 1 ','name_dr' => 'ناحیه 1 ','name_pa' => 'ناحیه 1 '],
            ['id' => '917','province_id' => '9','name_en' => 'PD 2 ','name_dr' => 'ناحیه 2 ','name_pa' => 'ناحیه 2 '],
            ['id' => '918','province_id' => '9','name_en' => 'PD 3 ','name_dr' => 'ناحیه 3 ','name_pa' => 'ناحیه 3 '],
            ['id' => '919','province_id' => '9','name_en' => 'PD 4 ','name_dr' => 'ناحیه 4 ','name_pa' => 'ناحیه 4 '],
            ['id' => '920','province_id' => '9','name_en' => 'Unknown ','name_dr' => 'نامعلوم ','name_pa' => 'نامعلوم '],
            ['id' => '1001','province_id' => '10','name_en' => 'PROVINCIAL CAPITAL OF  BAMYAN ( BAMYAN )','name_dr' => '( مرکز ولایت بامیان) بامیان','name_pa' => '( مرکز ولایت بامیان) بامیان'],
            ['id' => '1002','province_id' => '10','name_en' => 'SHEBAR','name_dr' => 'شیبر','name_pa' => 'شیبر'],
            ['id' => '1003','province_id' => '10','name_en' => 'SAIGHAN','name_dr' => 'سیغان','name_pa' => 'سیغان'],
            ['id' => '1004','province_id' => '10','name_en' => 'KAHMARD','name_dr' => 'کهمرد','name_pa' => 'کهمرد'],
            ['id' => '1005','province_id' => '10','name_en' => 'YAKAWLANG','name_dr' => 'یکاولنگ','name_pa' => 'یکاولنگ'],
            ['id' => '1006','province_id' => '10','name_en' => 'PANJAB','name_dr' => 'پنجاب','name_pa' => 'پنجاب'],
            ['id' => '1007','province_id' => '10','name_en' => 'WARAS','name_dr' => 'ورس','name_pa' => 'ورس'],
            ['id' => '1008','province_id' => '10','name_en' => 'Unknown ','name_dr' => 'نامعلوم ','name_pa' => 'نامعلوم '],
            ['id' => '1101','province_id' => '11','name_en' => 'PROVINCIAL CAPITAL OF  GHAZNI ( GHAZNI )','name_dr' => '(مرکز ولایت غزنی) غزنی','name_pa' => '(مرکز ولایت غزنی) غزنی'],
            ['id' => '1102','province_id' => '11','name_en' => 'WALI MOHAMMAD SHAHID KHUGYANI','name_dr' => 'ولی محمد شهید خوگیانی','name_pa' => 'ولی محمد شهید خوگیانی'],
            ['id' => '1103','province_id' => '11','name_en' => 'KHWAJA OMARI','name_dr' => 'خواجه عمری','name_pa' => 'خواجه عمری'],
            ['id' => '1104','province_id' => '11','name_en' => 'WAGHAZ','name_dr' => 'واغظ','name_pa' => 'واغظ'],
            ['id' => '1105','province_id' => '11','name_en' => 'DEH YAK','name_dr' => 'ده یک','name_pa' => 'ده یک'],
            ['id' => '1106','province_id' => '11','name_en' => 'JAGHATU','name_dr' => 'جغتو','name_pa' => 'جغتو'],
            ['id' => '1107','province_id' => '11','name_en' => 'ANDAR','name_dr' => 'اندر','name_pa' => 'اندر'],
            ['id' => '1108','province_id' => '11','name_en' => 'ZANAKHAN','name_dr' => 'زنخان','name_pa' => 'زنخان'],
            ['id' => '1109','province_id' => '11','name_en' => 'RASHIDAN','name_dr' => 'رشیدان','name_pa' => 'رشیدان'],
            ['id' => '1110','province_id' => '11','name_en' => 'NAWUR','name_dr' => 'ناور','name_pa' => 'ناور'],
            ['id' => '1111','province_id' => '11','name_en' => 'QARA BAGH','name_dr' => 'قره باغ','name_pa' => 'قره باغ'],
            ['id' => '1112','province_id' => '11','name_en' => 'GIRO','name_dr' => 'گیرو','name_pa' => 'گیرو'],
            ['id' => '1113','province_id' => '11','name_en' => 'AB BAND','name_dr' => 'آب بند','name_pa' => 'آب بند'],
            ['id' => '1114','province_id' => '11','name_en' => 'JAGHURI','name_dr' => 'جاغوری','name_pa' => 'جاغوری'],
            ['id' => '1115','province_id' => '11','name_en' => 'MUQUR','name_dr' => 'مقر','name_pa' => 'مقر'],
            ['id' => '1116','province_id' => '11','name_en' => 'MALISTAN','name_dr' => 'مالستان','name_pa' => 'مالستان'],
            ['id' => '1117','province_id' => '11','name_en' => 'GELAN','name_dr' => 'گیلان','name_pa' => 'گیلان'],
            ['id' => '1118','province_id' => '11','name_en' => 'AJRISTAN','name_dr' => 'اجرستان','name_pa' => 'اجرستان'],
            ['id' => '1119','province_id' => '11','name_en' => 'NAWA','name_dr' => 'ناوه','name_pa' => 'ناوه'],
            ['id' => '1120','province_id' => '11','name_en' => 'Unknown','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '1201','province_id' => '12','name_en' => ' PROVINCIAL CAPITAL OF  PAKTIKA ( SHARAN )','name_dr' => '( مرکز ولایت پکتیکا) شرن','name_pa' => '( مرکز ولایت پکتیکا) شرن'],
            ['id' => '1202','province_id' => '12','name_en' => 'MATA KHAN','name_dr' => 'متاخان','name_pa' => 'متاخان'],
            ['id' => '1203','province_id' => '12','name_en' => 'YOSUF KHEL','name_dr' => 'یوسف خیل','name_pa' => 'یوسف خیل'],
            ['id' => '1204','province_id' => '12','name_en' => 'YAHYA KHEL','name_dr' => 'یحیی خیل','name_pa' => 'یحیی خیل'],
            ['id' => '1205','province_id' => '12','name_en' => 'SAR RAWZA','name_dr' => 'سرروضه','name_pa' => 'سرروضه'],
            ['id' => '1206','province_id' => '12','name_en' => 'OMNA','name_dr' => 'اومنه','name_pa' => 'اومنه'],
            ['id' => '1207','province_id' => '12','name_en' => 'ZARGHUN SHAHR','name_dr' => 'زرغون شهر','name_pa' => 'زرغون شهر'],
            ['id' => '1208','province_id' => '12','name_en' => 'GOMAL','name_dr' => 'گومل','name_pa' => 'گومل'],
            ['id' => '1209','province_id' => '12','name_en' => 'JANI KHEL','name_dr' => 'جانی خیل','name_pa' => 'جانی خیل'],
            ['id' => '1210','province_id' => '12','name_en' => 'SURUBI','name_dr' => 'سروبی','name_pa' => 'سروبی'],
            ['id' => '1211','province_id' => '12','name_en' => 'URGOON','name_dr' => 'اورگون','name_pa' => 'اورگون'],
            ['id' => '1212','province_id' => '12','name_en' => 'ZIRUK','name_dr' => 'زیروک','name_pa' => 'زیروک'],
            ['id' => '1213','province_id' => '12','name_en' => 'NIKA','name_dr' => 'نیکه','name_pa' => 'نیکه'],
            ['id' => '1214','province_id' => '12','name_en' => 'BARMAL','name_dr' => 'برمل','name_pa' => 'برمل'],
            ['id' => '1215','province_id' => '12','name_en' => 'GIYAN','name_dr' => 'گیان','name_pa' => 'گیان'],
            ['id' => '1216','province_id' => '12','name_en' => 'DILA WA KHUSHAMAND','name_dr' => 'دیله و خوش آمند','name_pa' => 'دیله و خوش آمند'],
            ['id' => '1217','province_id' => '12','name_en' => 'WAZAKHWAH','name_dr' => 'وازه خوا','name_pa' => 'وازه خوا'],
            ['id' => '1218','province_id' => '12','name_en' => 'WORMAMAY','name_dr' => 'ورممی','name_pa' => 'ورممی'],
            ['id' => '1219','province_id' => '12','name_en' => 'TURWO','name_dr' => 'تروو','name_pa' => 'تروو'],
            ['id' => '1220','province_id' => '12','name_en' => 'Unknown','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '1301','province_id' => '13','name_en' => 'PROVINCIAL CAPITAL OF PAKTYA ( GARDEZ )','name_dr' => '(مرکز ولایت پکتیا) گردیز','name_pa' => '(مرکز ولایت پکتیا) گردیز'],
            ['id' => '1302','province_id' => '13','name_en' => 'AHMADABA','name_dr' => 'احمدآبا','name_pa' => 'احمدآبا'],
            ['id' => '1303','province_id' => '13','name_en' => 'ZURMAT','name_dr' => 'زرمت','name_pa' => 'زرمت'],
            ['id' => '1304','province_id' => '13','name_en' => 'SHWAK','name_dr' => 'شواک','name_pa' => 'شواک'],
            ['id' => '1305','province_id' => '13','name_en' => 'WUZA ZADRAN','name_dr' => 'وزی ځدران','name_pa' => 'وزی ځدران'],
            ['id' => '1306','province_id' => '13','name_en' => 'SAYYID KARAM','name_dr' => 'سیدکرم','name_pa' => 'سیدکرم'],
            ['id' => '1307','province_id' => '13','name_en' => 'JAJI','name_dr' => 'جاجی','name_pa' => 'جاجی'],
            ['id' => '1308','province_id' => '13','name_en' => 'LAJA AHMAD KHEL','name_dr' => 'لجه احمدخیل','name_pa' => 'لجه احمدخیل'],
            ['id' => '1309','province_id' => '13','name_en' => 'JANI KHEL','name_dr' => 'جانی خیل','name_pa' => 'جانی خیل'],
            ['id' => '1310','province_id' => '13','name_en' => 'SAMKANI','name_dr' => 'څمکنی','name_pa' => 'څمکنی'],
            ['id' => '1311','province_id' => '13','name_en' => 'DAND PATAN','name_dr' => 'دند پتان','name_pa' => 'دند پتان'],
            ['id' => '1312','province_id' => '13','name_en' => 'Unknown','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '1401','province_id' => '14','name_en' => 'PROVINCIAL CAPITAL OF KHOST ( KHOST )','name_dr' => '(مرکز ولایت خوست) خوست','name_pa' => '(مرکز ولایت خوست) خوست'],
            ['id' => '1402','province_id' => '14','name_en' => 'MANDUZAY (ESMAYEL KHEL)','name_dr' => '(مندوزی) اسماعیل خیل','name_pa' => '(مندوزی) اسماعیل خیل'],
            ['id' => '1403','province_id' => '14','name_en' => 'GURBUZ','name_dr' => 'گربز','name_pa' => 'گربز'],
            ['id' => '1404','province_id' => '14','name_en' => 'TANAY','name_dr' => 'تنی','name_pa' => 'تنی'],
            ['id' => '1405','province_id' => '14','name_en' => 'MUSA KHEL','name_dr' => 'موسی خیل','name_pa' => 'موسی خیل'],
            ['id' => '1406','province_id' => '14','name_en' => 'NADIRSHAH KOT','name_dr' => 'نادرشاه کوت','name_pa' => 'نادرشاه کوت'],
            ['id' => '1407','province_id' => '14','name_en' => 'SABARI (YAQUBI)','name_dr' => '(صبری) یعقوبی','name_pa' => '(صبری) یعقوبی'],
            ['id' => '1408','province_id' => '14','name_en' => 'ALI SHER','name_dr' => 'علی شیر','name_pa' => 'علی شیر'],
            ['id' => '1409','province_id' => '14','name_en' => 'BAAK','name_dr' => 'باک','name_pa' => 'باک'],
            ['id' => '1410','province_id' => '14','name_en' => 'QALANDAR','name_dr' => 'قلندر','name_pa' => 'قلندر'],
            ['id' => '1411','province_id' => '14','name_en' => 'SPERA','name_dr' => 'اسپیره','name_pa' => 'اسپیره'],
            ['id' => '1412','province_id' => '14','name_en' => 'SHAMUL','name_dr' => 'شمل','name_pa' => 'شمل'],
            ['id' => '1413','province_id' => '14','name_en' => 'ZAZI MAIDAN','name_dr' => 'ځاځی میدان','name_pa' => 'ځاځی میدان'],
            ['id' => '1414','province_id' => '14','name_en' => 'Unknown','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '1501','province_id' => '15','name_en' => 'PROVINCIAL CAPITAL OF KUNARHA ( ASAD ABAD )','name_dr' => '(مرکز ولایت کنرها) اسدآباد','name_pa' => '(مرکز ولایت کنرها) اسدآباد'],
            ['id' => '1502','province_id' => '15','name_en' => 'MARA WARA','name_dr' => 'مره وره','name_pa' => 'مره وره'],
            ['id' => '1503','province_id' => '15','name_en' => 'WATAPOOR','name_dr' => 'واته پور','name_pa' => 'واته پور'],
            ['id' => '1504','province_id' => '15','name_en' => 'NARANG WA BADIL','name_dr' => 'نرنگ وبادیل','name_pa' => 'نرنگ وبادیل'],
            ['id' => '1505','province_id' => '15','name_en' => 'SAR KANI','name_dr' => 'سرکانی','name_pa' => 'سرکانی'],
            ['id' => '1506','province_id' => '15','name_en' => 'SHIGAL WA SHELTAN','name_dr' => 'شیگل و شیلتن','name_pa' => 'شیگل و شیلتن'],
            ['id' => '1507','province_id' => '15','name_en' => 'DARA-E-PECH','name_dr' => 'دره پیچ','name_pa' => 'دره پیچ'],
            ['id' => '1508','province_id' => '15','name_en' => 'BAR KUNAR','name_dr' => 'برکنر','name_pa' => 'برکنر'],
            ['id' => '1509','province_id' => '15','name_en' => 'SAWKAI','name_dr' => 'څوکی','name_pa' => 'څوکی'],
            ['id' => '1510','province_id' => '15','name_en' => 'KHAS KUNAR','name_dr' => 'خاص کنر','name_pa' => 'خاص کنر'],
            ['id' => '1511','province_id' => '15','name_en' => 'GHAZI ABAD','name_dr' => 'غازی آباد','name_pa' => 'غازی آباد'],
            ['id' => '1512','province_id' => '15','name_en' => 'DANGAM','name_dr' => 'دانگام','name_pa' => 'دانگام'],
            ['id' => '1513','province_id' => '15','name_en' => 'CHAPA DARA','name_dr' => 'چپه دره','name_pa' => 'چپه دره'],
            ['id' => '1514','province_id' => '15','name_en' => 'NOOR GAL','name_dr' => 'نورگل','name_pa' => 'نورگل'],
            ['id' => '1515','province_id' => '15','name_en' => 'NARI','name_dr' => 'نری','name_pa' => 'نری'],
            ['id' => '1516','province_id' => '15','name_en' => 'Unknown','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '1601','province_id' => '16','name_en' => 'PROVINCIAL CAPITAL OF NOORISTAN ( PAROON )','name_dr' => '( مرکز ولایت نورستان) پارون','name_pa' => '( مرکز ولایت نورستان) پارون'],
            ['id' => '1602','province_id' => '16','name_en' => 'WAYGAL','name_dr' => 'وایگل','name_pa' => 'وایگل'],
            ['id' => '1603','province_id' => '16','name_en' => 'WAMA','name_dr' => 'واما','name_pa' => 'واما'],
            ['id' => '1604','province_id' => '16','name_en' => 'NOOR GRAM','name_dr' => 'نورگرام','name_pa' => 'نورگرام'],
            ['id' => '1605','province_id' => '16','name_en' => 'DUAB','name_dr' => 'دوآب','name_pa' => 'دوآب'],
            ['id' => '1606','province_id' => '16','name_en' => 'KAMDESH','name_dr' => 'کامدیش','name_pa' => 'کامدیش'],
            ['id' => '1607','province_id' => '16','name_en' => 'MANDOL','name_dr' => 'مندول','name_pa' => 'مندول'],
            ['id' => '1608','province_id' => '16','name_en' => 'BARG-E-MATAL','name_dr' => 'برگ متال','name_pa' => 'برگ متال'],
            ['id' => '1609','province_id' => '16','name_en' => 'Unknown','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '1701','province_id' => '17','name_en' => 'PROVINCIAL CAPITAL OF BADAKHSHAN ( FAIZ ABAD )','name_dr' => '( مرکز ولایت بدخشان) فیض آباد','name_pa' => '( مرکز ولایت بدخشان) فیض آباد'],
            ['id' => '1702','province_id' => '17','name_en' => 'ARGO','name_dr' => 'ارگو','name_pa' => 'ارگو'],
            ['id' => '1703','province_id' => '17','name_en' => 'ARGHANJ KHWAH','name_dr' => 'ارغنجخواه','name_pa' => 'ارغنجخواه'],
            ['id' => '1704','province_id' => '17','name_en' => 'YAFTAL-E-SOFLA','name_dr' => 'یفتل سفلی','name_pa' => 'یفتل سفلی'],
            ['id' => '1705','province_id' => '17','name_en' => 'KHASH','name_dr' => 'خاش','name_pa' => 'خاش'],
            ['id' => '1706','province_id' => '17','name_en' => 'BAHARAK','name_dr' => 'بهارک','name_pa' => 'بهارک'],
            ['id' => '1707','province_id' => '17','name_en' => 'DARAYIM','name_dr' => 'درایم','name_pa' => 'درایم'],
            ['id' => '1708','province_id' => '17','name_en' => 'KOHISTAN','name_dr' => 'کوهستان','name_pa' => 'کوهستان'],
            ['id' => '1709','province_id' => '17','name_en' => 'YAWAN','name_dr' => 'یاوان','name_pa' => 'یاوان'],
            ['id' => '1710','province_id' => '17','name_en' => 'JURM','name_dr' => 'جرم','name_pa' => 'جرم'],
            ['id' => '1711','province_id' => '17','name_en' => 'TASHKAN','name_dr' => 'تشکان','name_pa' => 'تشکان'],
            ['id' => '1712','province_id' => '17','name_en' => 'SHUHADA','name_dr' => 'شهدا','name_pa' => 'شهدا'],
            ['id' => '1713','province_id' => '17','name_en' => 'SHAHR-E-BUZURG','name_dr' => 'شهربزرگ','name_pa' => 'شهربزرگ'],
            ['id' => '1714','province_id' => '17','name_en' => 'RAGHISTAN','name_dr' => 'راغستان','name_pa' => 'راغستان'],
            ['id' => '1715','province_id' => '17','name_en' => 'KISHM','name_dr' => 'کشم','name_pa' => 'کشم'],
            ['id' => '1716','province_id' => '17','name_en' => 'WARDOOJ','name_dr' => 'وردوج','name_pa' => 'وردوج'],
            ['id' => '1717','province_id' => '17','name_en' => 'TAGAB','name_dr' => 'تگاب','name_pa' => 'تگاب'],
            ['id' => '1718','province_id' => '17','name_en' => 'YAMGAN','name_dr' => 'یمگان','name_pa' => 'یمگان'],
            ['id' => '1719','province_id' => '17','name_en' => 'SHIGHNAN','name_dr' => 'شغنان','name_pa' => 'شغنان'],
            ['id' => '1720','province_id' => '17','name_en' => 'KHWAHAN','name_dr' => 'خواهان','name_pa' => 'خواهان'],
            ['id' => '1721','province_id' => '17','name_en' => 'KUFAB','name_dr' => 'کوف آب','name_pa' => 'کوف آب'],
            ['id' => '1722','province_id' => '17','name_en' => 'DARWAZ-E-PAYIN (MAMAY)','name_dr' => 'درواز پائین مایمی','name_pa' => 'درواز پائین مایمی'],
            ['id' => '1723','province_id' => '17','name_en' => 'ESHKASHIM','name_dr' => 'اشکاشم','name_pa' => 'اشکاشم'],
            ['id' => '1724','province_id' => '17','name_en' => 'SHIKI','name_dr' => 'شکی','name_pa' => 'شکی'],
            ['id' => '1725','province_id' => '17','name_en' => 'ZEBAK','name_dr' => 'زیباک','name_pa' => 'زیباک'],
            ['id' => '1726','province_id' => '17','name_en' => 'KIRAN WA MENJAN','name_dr' => 'کران ومنجان','name_pa' => 'کران ومنجان'],
            ['id' => '1727','province_id' => '17','name_en' => 'DARWAZ-E-BALA (NESAY)','name_dr' => 'درواز بالا نسی','name_pa' => 'درواز بالا نسی'],
            ['id' => '1728','province_id' => '17','name_en' => 'WAKHAN','name_dr' => 'واخان','name_pa' => 'واخان'],
            ['id' => '1729','province_id' => '17','name_en' => 'PD 1 ','name_dr' => 'ناحیه 1 ','name_pa' => 'ناحیه 1 '],
            ['id' => '1730','province_id' => '17','name_en' => 'PD 2 ','name_dr' => 'ناحیه 2 ','name_pa' => 'ناحیه 2 '],
            ['id' => '1731','province_id' => '17','name_en' => 'PD 3 ','name_dr' => 'ناحیه 3 ','name_pa' => 'ناحیه 3 '],
            ['id' => '1732','province_id' => '17','name_en' => 'PD 4 ','name_dr' => 'ناحیه 4 ','name_pa' => 'ناحیه 4 '],
            ['id' => '1733','province_id' => '17','name_en' => 'PD 5 ','name_dr' => 'ناحیه 5 ','name_pa' => 'ناحیه 5 '],
            ['id' => '1734','province_id' => '17','name_en' => 'PD 6 ','name_dr' => 'ناحیه 6 ','name_pa' => 'ناحیه 6 '],
            ['id' => '1735','province_id' => '17','name_en' => 'PD 7 ','name_dr' => 'ناحیه 7 ','name_pa' => 'ناحیه 7 '],
            ['id' => '1736','province_id' => '17','name_en' => 'PD 8 ','name_dr' => 'ناحیه 8 ','name_pa' => 'ناحیه 8 '],
            ['id' => '1737','province_id' => '17','name_en' => 'PD 9 ','name_dr' => 'ناحیه 9 ','name_pa' => 'ناحیه 9 '],
            ['id' => '1738','province_id' => '17','name_en' => 'PD 10 ','name_dr' => 'ناحیه 10 ','name_pa' => 'ناحیه 10 '],
            ['id' => '1739','province_id' => '17','name_en' => 'PD 11 ','name_dr' => 'ناحیه 11 ','name_pa' => 'ناحیه 11 '],
            ['id' => '1740','province_id' => '17','name_en' => 'Unknown ','name_dr' => 'نامعلوم ','name_pa' => 'نامعلوم '],
            ['id' => '1801','province_id' => '18','name_en' => 'PROVINCIAL CAPITAL OF TAKHAR ( TALUQAN )','name_dr' => '( مرکز ولایت تخار) تالقان','name_pa' => '( مرکز ولایت تخار) تالقان'],
            ['id' => '1802','province_id' => '18','name_en' => 'HAZAR SUMUCH','name_dr' => 'هزارسموچ','name_pa' => 'هزارسموچ'],
            ['id' => '1803','province_id' => '18','name_en' => 'BAHARAK','name_dr' => 'بهارک','name_pa' => 'بهارک'],
            ['id' => '1804','province_id' => '18','name_en' => 'BANGI','name_dr' => 'بنگی','name_pa' => 'بنگی'],
            ['id' => '1805','province_id' => '18','name_en' => 'CHAL','name_dr' => 'چال','name_pa' => 'چال'],
            ['id' => '1806','province_id' => '18','name_en' => 'NAMAK AB','name_dr' => 'نمک آب','name_pa' => 'نمک آب'],
            ['id' => '1807','province_id' => '18','name_en' => 'KALAFGAN','name_dr' => 'کلفگان','name_pa' => 'کلفگان'],
            ['id' => '1808','province_id' => '18','name_en' => 'FARKHAR','name_dr' => 'فرخار','name_pa' => 'فرخار'],
            ['id' => '1809','province_id' => '18','name_en' => 'KHWAJA GHAR','name_dr' => 'خواجه غار','name_pa' => 'خواجه غار'],
            ['id' => '1810','province_id' => '18','name_en' => 'RUSTAQ','name_dr' => 'رستاق','name_pa' => 'رستاق'],
            ['id' => '1811','province_id' => '18','name_en' => 'ESHKAMESH','name_dr' => 'اشکمش','name_pa' => 'اشکمش'],
            ['id' => '1812','province_id' => '18','name_en' => 'DASHT-E-QALA','name_dr' => 'دشت قلعه','name_pa' => 'دشت قلعه'],
            ['id' => '1813','province_id' => '18','name_en' => 'WARSAJ','name_dr' => 'ورسج','name_pa' => 'ورسج'],
            ['id' => '1814','province_id' => '18','name_en' => 'KHWAJA BAHAWUDDIN','name_dr' => 'خواجه بهاوالدین','name_pa' => 'خواجه بهاوالدین'],
            ['id' => '1815','province_id' => '18','name_en' => 'DARQAD','name_dr' => 'درقد','name_pa' => 'درقد'],
            ['id' => '1816','province_id' => '18','name_en' => 'CHAHAB','name_dr' => 'چاه آب','name_pa' => 'چاه آب'],
            ['id' => '1817','province_id' => '18','name_en' => 'YANGI QALA','name_dr' => 'ینگی قلعه','name_pa' => 'ینگی قلعه'],
            ['id' => '1818','province_id' => '18','name_en' => 'PD 1 ','name_dr' => 'ناحیه 1 ','name_pa' => 'ناحیه 1 '],
            ['id' => '1819','province_id' => '18','name_en' => 'PD 2 ','name_dr' => 'ناحیه 2 ','name_pa' => 'ناحیه 2 '],
            ['id' => '1820','province_id' => '18','name_en' => 'PD 3 ','name_dr' => 'ناحیه 3 ','name_pa' => 'ناحیه 3 '],
            ['id' => '1821','province_id' => '18','name_en' => 'PD 4 ','name_dr' => 'ناحیه 4 ','name_pa' => 'ناحیه 4 '],
            ['id' => '1822','province_id' => '18','name_en' => 'Unknown ','name_dr' => 'نامعلوم ','name_pa' => 'نامعلوم '],
            ['id' => '1823','province_id' => '18','name_en' => 'Gul bad','name_dr' => 'کل باد','name_pa' => 'کل باد'],
            ['id' => '1901','province_id' => '19','name_en' => 'PROVINCIAL CAPITAL OF KUNDUZ ( KUNDUZ )','name_dr' => '(مرکز ولایت کندز) کندز','name_pa' => '(مرکز ولایت کندز) کندز'],
            ['id' => '1902','province_id' => '19','name_en' => 'CHAR DARAH','name_dr' => 'چاردره','name_pa' => 'چاردره'],
            ['id' => '1903','province_id' => '19','name_en' => 'ALI ABAD','name_dr' => 'علی آباد','name_pa' => 'علی آباد'],
            ['id' => '1904','province_id' => '19','name_en' => 'KHAN ABAD','name_dr' => 'خان آباد','name_pa' => 'خان آباد'],
            ['id' => '1905','province_id' => '19','name_en' => 'HAZRATI IMAM SAHIB','name_dr' => 'حضرت امام صاحب','name_pa' => 'حضرت امام صاحب'],
            ['id' => '1906','province_id' => '19','name_en' => 'DASHTI-E-ARCHI','name_dr' => 'دشت ارچی','name_pa' => 'دشت ارچی'],
            ['id' => '1907','province_id' => '19','name_en' => 'QALA-E-ZAL','name_dr' => 'قلعه ذال','name_pa' => 'قلعه ذال'],
            ['id' => '1908','province_id' => '19','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '1909','province_id' => '19','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '1910','province_id' => '19','name_en' => 'PD 2','name_dr' => 'ناحیه 2','name_pa' => 'ناحیه 2'],
            ['id' => '1911','province_id' => '19','name_en' => 'PD 3','name_dr' => 'ناحیه 3','name_pa' => 'ناحیه 3'],
            ['id' => '1912','province_id' => '19','name_en' => 'PD 4','name_dr' => 'ناحیه 4','name_pa' => 'ناحیه 4'],
            ['id' => '1913','province_id' => '19','name_en' => 'PD 5','name_dr' => 'ناحیه 5','name_pa' => 'ناحیه 5'],
            ['id' => '2001','province_id' => '20','name_en' => 'PROVINCIAL CAPITAL OF SAMANGAN ( AYBAK )','name_dr' => '( مرکز ولایت سمنگان) ایبک','name_pa' => '( مرکز ولایت سمنگان) ایبک'],
            ['id' => '2002','province_id' => '20','name_en' => 'HAZRAT-E-SULTAN','name_dr' => 'حضرت سلطان','name_pa' => 'حضرت سلطان'],
            ['id' => '2003','province_id' => '20','name_en' => 'KHURAM WA SARBAGH','name_dr' => 'خرم و سارباغ','name_pa' => 'خرم و سارباغ'],
            ['id' => '2004','province_id' => '20','name_en' => 'FEROZ NAKHCHEER','name_dr' => 'فیروزنخچیر','name_pa' => 'فیروزنخچیر'],
            ['id' => '2005','province_id' => '20','name_en' => 'ROI-DO-AB','name_dr' => 'روی دوآب','name_pa' => 'روی دوآب'],
            ['id' => '2006','province_id' => '20','name_en' => 'DARA-E-SOOF-E-PAYIN','name_dr' => 'دره صوف پائین','name_pa' => 'دره صوف پائین'],
            ['id' => '2007','province_id' => '20','name_en' => 'DARA-E-SOOF-E-BALA','name_dr' => 'دره صوف  بالا','name_pa' => 'دره صوف  بالا'],
            ['id' => '2008','province_id' => '20','name_en' => 'PD 3','name_dr' => 'ناحیه 3','name_pa' => 'ناحیه 3'],
            ['id' => '2009','province_id' => '20','name_en' => 'Unknown','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '2010','province_id' => '20','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '2011','province_id' => '20','name_en' => 'PD 2','name_dr' => 'ناحیه 2','name_pa' => 'ناحیه 2'],
            ['id' => '2102','province_id' => '21','name_en' => 'NAHR-E-SHAHI','name_dr' => 'نهر شاهی','name_pa' => 'نهر شاهی'],
            ['id' => '2103','province_id' => '21','name_en' => 'DEHDADI','name_dr' => 'دهدادی','name_pa' => 'دهدادی'],
            ['id' => '2104','province_id' => '21','name_en' => 'CHAR KENT','name_dr' => 'چارکنت','name_pa' => 'چارکنت'],
            ['id' => '2105','province_id' => '21','name_en' => 'MARMUL','name_dr' => 'مارمل','name_pa' => 'مارمل'],
            ['id' => '2106','province_id' => '21','name_en' => 'BALKH','name_dr' => 'بلخ','name_pa' => 'بلخ'],
            ['id' => '2107','province_id' => '21','name_en' => 'SHOLGARA','name_dr' => 'شولگره','name_pa' => 'شولگره'],
            ['id' => '2108','province_id' => '21','name_en' => 'CHIMTAL','name_dr' => 'چمتال','name_pa' => 'چمتال'],
            ['id' => '2109','province_id' => '21','name_en' => 'DAWLAT ABAD','name_dr' => 'دولت آباد','name_pa' => 'دولت آباد'],
            ['id' => '2110','province_id' => '21','name_en' => 'KHULM','name_dr' => 'خلم','name_pa' => 'خلم'],
            ['id' => '2111','province_id' => '21','name_en' => 'CHAR BOLAK','name_dr' => 'چاربولک','name_pa' => 'چاربولک'],
            ['id' => '2112','province_id' => '21','name_en' => 'SHORTEPA','name_dr' => 'شورتیپه','name_pa' => 'شورتیپه'],
            ['id' => '2113','province_id' => '21','name_en' => 'KALDAR','name_dr' => 'کلدار','name_pa' => 'کلدار'],
            ['id' => '2114','province_id' => '21','name_en' => 'KISHINDEH','name_dr' => 'کشنده','name_pa' => 'کشنده'],
            ['id' => '2115','province_id' => '21','name_en' => 'ZARI','name_dr' => 'زاری','name_pa' => 'زاری'],
            ['id' => '2116','province_id' => '21','name_en' => 'Ailaq che paeen','name_dr' => 'ایلقچی پاین','name_pa' => 'ایلقچی پاین'],
            ['id' => '2117','province_id' => '21','name_en' => 'PD 1 ','name_dr' => 'ناحیه 1 ','name_pa' => 'ناحیه 1 '],
            ['id' => '2118','province_id' => '21','name_en' => 'PD 2 ','name_dr' => 'ناحیه 2 ','name_pa' => 'ناحیه 2 '],
            ['id' => '2119','province_id' => '21','name_en' => 'PD 3 ','name_dr' => 'ناحیه 3 ','name_pa' => 'ناحیه 3 '],
            ['id' => '2120','province_id' => '21','name_en' => 'PD 4 ','name_dr' => 'ناحیه 4 ','name_pa' => 'ناحیه 4 '],
            ['id' => '2121','province_id' => '21','name_en' => 'PD 5 ','name_dr' => 'ناحیه 5 ','name_pa' => 'ناحیه 5 '],
            ['id' => '2122','province_id' => '21','name_en' => 'PD 6 ','name_dr' => 'ناحیه 6 ','name_pa' => 'ناحیه 6 '],
            ['id' => '2123','province_id' => '21','name_en' => 'PD 7 ','name_dr' => 'ناحیه 7 ','name_pa' => 'ناحیه 7 '],
            ['id' => '2124','province_id' => '21','name_en' => 'PD 8 ','name_dr' => 'ناحیه 8 ','name_pa' => 'ناحیه 8 '],
            ['id' => '2125','province_id' => '21','name_en' => 'PD 9 ','name_dr' => 'ناحیه 9 ','name_pa' => 'ناحیه 9 '],
            ['id' => '2126','province_id' => '21','name_en' => 'Unknown ','name_dr' => 'نامعلوم ','name_pa' => 'نامعلوم '],
            ['id' => '2127','province_id' => '21','name_en' => 'Provincial Capital of Balkh (Mazar-e-sharif)','name_dr' => '(مرکز ولایت بلخ) مزار شریف','name_pa' => '(مرکز ولایت بلخ) مزار شریف'],
            ['id' => '2201','province_id' => '22','name_en' => 'PROVINCIAL CAPITAL OF SAR-E-PUL (SAR-E-PUL)','name_dr' => '( مرکزولایت سرپل) سرپل','name_pa' => '( مرکزولایت سرپل) سرپل'],
            ['id' => '2202','province_id' => '22','name_en' => 'SAYYAD','name_dr' => 'صیاد','name_pa' => 'صیاد'],
            ['id' => '2203','province_id' => '22','name_en' => 'KOHISTANAT','name_dr' => 'کوهستانات','name_pa' => 'کوهستانات'],
            ['id' => '2204','province_id' => '22','name_en' => 'SOZMA QALA','name_dr' => 'سوزمه قلعه','name_pa' => 'سوزمه قلعه'],
            ['id' => '2205','province_id' => '22','name_en' => 'SANGCHARAK','name_dr' => 'سنگ چارک','name_pa' => 'سنگ چارک'],
            ['id' => '2206','province_id' => '22','name_en' => 'GOSFANDI','name_dr' => 'گوسفندی','name_pa' => 'گوسفندی'],
            ['id' => '2207','province_id' => '22','name_en' => 'BALKHAB','name_dr' => 'بلخاب','name_pa' => 'بلخاب'],
            ['id' => '2208','province_id' => '22','name_en' => 'Unknown','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '2209','province_id' => '22','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '2210','province_id' => '22','name_en' => 'PD 2','name_dr' => 'ناحیه 2','name_pa' => 'ناحیه 2'],
            ['id' => '2301','province_id' => '23','name_en' => 'PROVINCIAL CAPITAL OF GHOR ( CHIGHCHERAN )','name_dr' => '( مرکز ولایت غور) چغچران','name_pa' => '( مرکز ولایت غور) چغچران'],
            ['id' => '2302','province_id' => '23','name_en' => 'DULEENA','name_dr' => 'دولینه','name_pa' => 'دولینه'],
            ['id' => '2303','province_id' => '23','name_en' => 'DAWLATYAR','name_dr' => 'دولت یار','name_pa' => 'دولت یار'],
            ['id' => '2304','province_id' => '23','name_en' => 'CHAR SADA','name_dr' => 'چارصده','name_pa' => 'چارصده'],
            ['id' => '2305','province_id' => '23','name_en' => 'PASABAND','name_dr' => 'پسابند','name_pa' => 'پسابند'],
            ['id' => '2306','province_id' => '23','name_en' => 'SHAHRAK','name_dr' => 'شهرک','name_pa' => 'شهرک'],
            ['id' => '2307','province_id' => '23','name_en' => 'LAL WA SARJANGAL','name_dr' => 'لعل وسرجنگل','name_pa' => 'لعل وسرجنگل'],
            ['id' => '2308','province_id' => '23','name_en' => 'TAYWARA','name_dr' => 'تیوره','name_pa' => 'تیوره'],
            ['id' => '2309','province_id' => '23','name_en' => 'TULAK','name_dr' => 'تولک','name_pa' => 'تولک'],
            ['id' => '2310','province_id' => '23','name_en' => 'SAGHAR','name_dr' => 'ساغر','name_pa' => 'ساغر'],
            ['id' => '2311','province_id' => '23','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '2312','province_id' => '23','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '2313','province_id' => '23','name_en' => 'PD 2','name_dr' => 'ناحیه 2','name_pa' => 'ناحیه 2'],
            ['id' => '2314','province_id' => '23','name_en' => 'PD 3','name_dr' => 'ناحیه 3','name_pa' => 'ناحیه 3'],
            ['id' => '2315','province_id' => '23','name_en' => 'PD 4','name_dr' => 'ناحیه 4','name_pa' => 'ناحیه 4'],
            ['id' => '2401','province_id' => '24','name_en' => 'PROVINCIAL CAPITAL OF DAYKUNDI ( NILI )','name_dr' => '(مرکز ولایت دایکندی) نیلی','name_pa' => '(مرکز ولایت دایکندی) نیلی'],
            ['id' => '2402','province_id' => '24','name_en' => 'SHAHRISTAN','name_dr' => 'شهرستان','name_pa' => 'شهرستان'],
            ['id' => '2403','province_id' => '24','name_en' => 'GIZAB','name_dr' => 'گیزاب','name_pa' => 'گیزاب'],
            ['id' => '2404','province_id' => '24','name_en' => 'ISHTERLAI','name_dr' => 'اشترلی','name_pa' => 'اشترلی'],
            ['id' => '2405','province_id' => '24','name_en' => 'KHEDIR','name_dr' => 'خدیر','name_pa' => 'خدیر'],
            ['id' => '2406','province_id' => '24','name_en' => 'GETI','name_dr' => 'گیتی','name_pa' => 'گیتی'],
            ['id' => '2407','province_id' => '24','name_en' => 'MIRAMOR','name_dr' => 'میرامور','name_pa' => 'میرامور'],
            ['id' => '2408','province_id' => '24','name_en' => 'SANG-E-TAKHT','name_dr' => 'سنگ تخت','name_pa' => 'سنگ تخت'],
            ['id' => '2409','province_id' => '24','name_en' => 'KEJRAN','name_dr' => 'کیجران','name_pa' => 'کیجران'],
            ['id' => '2410','province_id' => '24','name_en' => 'Unknown','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '2411','province_id' => '24','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '2501','province_id' => '25','name_en' => 'PROVINCIAL CAPITAL OF  UROZGAN ( TIRINKOT )','name_dr' => ' (مرکز ولایت ارزگان) ترینکوت','name_pa' => ' (مرکز ولایت ارزگان) ترینکوت'],
            ['id' => '2502','province_id' => '25','name_en' => 'DEHRAOUD','name_dr' => 'دهراود','name_pa' => 'دهراود'],
            ['id' => '2503','province_id' => '25','name_en' => 'CHORA','name_dr' => 'چوره','name_pa' => 'چوره'],
            ['id' => '2504','province_id' => '25','name_en' => 'SHAHID-E-HASSAS','name_dr' => 'شهید حساس','name_pa' => 'شهید حساس'],
            ['id' => '2505','province_id' => '25','name_en' => 'KHAS UROZGAN','name_dr' => 'خاص ارزگان','name_pa' => 'خاص ارزگان'],
            ['id' => '2506','province_id' => '25','name_en' => 'PD 1 ','name_dr' => 'ناحیه 1 ','name_pa' => 'ناحیه 1 '],
            ['id' => '2507','province_id' => '25','name_en' => 'PD 2 ','name_dr' => 'ناحیه 2 ','name_pa' => 'ناحیه 2 '],
            ['id' => '2508','province_id' => '25','name_en' => 'PD 3 ','name_dr' => 'ناحیه 3 ','name_pa' => 'ناحیه 3 '],
            ['id' => '2509','province_id' => '25','name_en' => 'PD 4 ','name_dr' => 'ناحیه 4 ','name_pa' => 'ناحیه 4 '],
            ['id' => '2510','province_id' => '25','name_en' => 'Unknown ','name_dr' => 'نامعلوم ','name_pa' => 'نامعلوم '],
            ['id' => '2511','province_id' => '25','name_en' => 'Chahar Chino','name_dr' => 'چهارچینو','name_pa' => 'چهارچینو'],
            ['id' => '2601','province_id' => '26','name_en' => 'PROVINCIAL CAPITAL OF  ZABUL ( QALAT ) ','name_dr' => '( مرکز ولایت زابل) قلات','name_pa' => '( مرکز ولایت زابل) قلات'],
            ['id' => '2602','province_id' => '26','name_en' => 'TARANK WA JALDAK','name_dr' => 'ترنک وجلدک','name_pa' => 'ترنک وجلدک'],
            ['id' => '2603','province_id' => '26','name_en' => 'SHINKAI','name_dr' => 'شینکی','name_pa' => 'شینکی'],
            ['id' => '2604','province_id' => '26','name_en' => 'MIZAN','name_dr' => 'میزان','name_pa' => 'میزان'],
            ['id' => '2605','province_id' => '26','name_en' => 'ARGHANDAB','name_dr' => 'ارغنداب','name_pa' => 'ارغنداب'],
            ['id' => '2606','province_id' => '26','name_en' => 'SHAH JOI','name_dr' => 'شاه جوی','name_pa' => 'شاه جوی'],
            ['id' => '2607','province_id' => '26','name_en' => 'DAICHOPAN','name_dr' => 'دایچوپان','name_pa' => 'دایچوپان'],
            ['id' => '2608','province_id' => '26','name_en' => 'ATGHAR','name_dr' => 'اتغر','name_pa' => 'اتغر'],
            ['id' => '2609','province_id' => '26','name_en' => 'NAW BAHAR','name_dr' => 'نوبهار','name_pa' => 'نوبهار'],
            ['id' => '2610','province_id' => '26','name_en' => 'SHEMEL ZAYEE','name_dr' => 'شملزایی','name_pa' => 'شملزایی'],
            ['id' => '2611','province_id' => '26','name_en' => 'KAKARI (KHAK-E-AFGHAN)','name_dr' => '(کاکری) خاک افغان','name_pa' => '(کاکری) خاک افغان'],
            ['id' => '2612','province_id' => '26','name_en' => 'Unknown','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '2701','province_id' => '27','name_en' => 'PROVINCIAL CAPITAL OF  KANDAHAR ( KANDAHAR )','name_dr' => '(مرکز ولایت کندهار) کندهار','name_pa' => '(مرکز ولایت کندهار) کندهار'],
            ['id' => '2702','province_id' => '27','name_en' => 'ARGHANDAB','name_dr' => 'ارغنداب','name_pa' => 'ارغنداب'],
            ['id' => '2703','province_id' => '27','name_en' => 'DAMAN','name_dr' => 'دامان','name_pa' => 'دامان'],
            ['id' => '2704','province_id' => '27','name_en' => 'PANJWAYEE','name_dr' => 'پنجوائی','name_pa' => 'پنجوائی'],
            ['id' => '2705','province_id' => '27','name_en' => 'ZHIRE','name_dr' => 'ژیری','name_pa' => 'ژیری'],
            ['id' => '2706','province_id' => '27','name_en' => 'SHAH WALI KOT','name_dr' => 'شاه ولی کوت','name_pa' => 'شاه ولی کوت'],
            ['id' => '2707','province_id' => '27','name_en' => 'KHAKREZ','name_dr' => 'خاکریز','name_pa' => 'خاکریز'],
            ['id' => '2708','province_id' => '27','name_en' => 'ARGHISTAN','name_dr' => 'ارغستان','name_pa' => 'ارغستان'],
            ['id' => '2709','province_id' => '27','name_en' => 'GHORAK','name_dr' => 'غورک','name_pa' => 'غورک'],
            ['id' => '2710','province_id' => '27','name_en' => 'MAIWAND','name_dr' => 'میوند','name_pa' => 'میوند'],
            ['id' => '2711','province_id' => '27','name_en' => 'SPIN BOLDAK','name_dr' => 'سپین بولدک','name_pa' => 'سپین بولدک'],
            ['id' => '2712','province_id' => '27','name_en' => 'NESH','name_dr' => 'نیش','name_pa' => 'نیش'],
            ['id' => '2713','province_id' => '27','name_en' => 'MIYANESHIN','name_dr' => 'میانشین','name_pa' => 'میانشین'],
            ['id' => '2714','province_id' => '27','name_en' => 'SHORABAK','name_dr' => 'شورابک','name_pa' => 'شورابک'],
            ['id' => '2715','province_id' => '27','name_en' => 'MARUF','name_dr' => 'معروف','name_pa' => 'معروف'],
            ['id' => '2716','province_id' => '27','name_en' => 'REG (SHIGA)','name_dr' => 'ریگ(شگه)','name_pa' => 'ریگ(شگه)'],
            ['id' => '2717','province_id' => '27','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '2718','province_id' => '27','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '2719','province_id' => '27','name_en' => 'PD 2','name_dr' => 'ناحیه 2','name_pa' => 'ناحیه 2'],
            ['id' => '2720','province_id' => '27','name_en' => 'PD 3','name_dr' => 'ناحیه 3','name_pa' => 'ناحیه 3'],
            ['id' => '2721','province_id' => '27','name_en' => 'PD 4','name_dr' => 'ناحیه 4','name_pa' => 'ناحیه 4'],
            ['id' => '2722','province_id' => '27','name_en' => 'PD 5','name_dr' => 'ناحیه 5','name_pa' => 'ناحیه 5'],
            ['id' => '2723','province_id' => '27','name_en' => 'PD 6','name_dr' => 'ناحیه 6','name_pa' => 'ناحیه 6'],
            ['id' => '2724','province_id' => '27','name_en' => 'PD 7','name_dr' => 'ناحیه 7','name_pa' => 'ناحیه 7'],
            ['id' => '2725','province_id' => '27','name_en' => 'PD 8','name_dr' => 'ناحیه 8','name_pa' => 'ناحیه 8'],
            ['id' => '2726','province_id' => '27','name_en' => 'PD 9','name_dr' => 'ناحیه 9','name_pa' => 'ناحیه 9'],
            ['id' => '2727','province_id' => '27','name_en' => 'PD 10','name_dr' => 'ناحیه 10','name_pa' => 'ناحیه 10'],
            ['id' => '2728','province_id' => '27','name_en' => 'PD 11','name_dr' => 'ناحیه 11','name_pa' => 'ناحیه 11'],
            ['id' => '2729','province_id' => '27','name_en' => 'PD 12','name_dr' => 'ناحیه 12','name_pa' => 'ناحیه 12'],
            ['id' => '2730','province_id' => '27','name_en' => 'PD 13','name_dr' => 'ناحیه 13','name_pa' => 'ناحیه 13'],
            ['id' => '2731','province_id' => '27','name_en' => 'PD 14','name_dr' => 'ناحیه 14','name_pa' => 'ناحیه 14'],
            ['id' => '2732','province_id' => '27','name_en' => 'PD 15','name_dr' => 'ناحیه 15','name_pa' => 'ناحیه 15'],
            ['id' => '2733','province_id' => '27','name_en' => 'PD 16','name_dr' => 'ناحیه 16','name_pa' => 'ناحیه 16'],
            ['id' => '2734','province_id' => '27','name_en' => 'PD 17','name_dr' => 'ناحیه 17','name_pa' => 'ناحیه 17'],
            ['id' => '2735','province_id' => '27','name_en' => 'Dand','name_dr' => 'دند','name_pa' => 'دند'],
            ['id' => '2801','province_id' => '28','name_en' => 'PROVINCIAL CAPITAL OF  JAWZJAN [ SHEBERGHAN ]','name_dr' => '( مرکز ولایت جوزجان) شبرغان','name_pa' => '( مرکز ولایت جوزجان) شبرغان'],
            ['id' => '2802','province_id' => '28','name_en' => 'KHWAJA DUKOH','name_dr' => 'خواجه دوکوه','name_pa' => 'خواجه دوکوه'],
            ['id' => '2803','province_id' => '28','name_en' => 'KHANAQA','name_dr' => 'خانقاً','name_pa' => 'خانقاً'],
            ['id' => '2804','province_id' => '28','name_en' => 'MINGAJIK','name_dr' => 'منگجیک','name_pa' => 'منگجیک'],
            ['id' => '2805','province_id' => '28','name_en' => 'QUSH TEPA','name_dr' => 'قوش تیپه','name_pa' => 'قوش تیپه'],
            ['id' => '2806','province_id' => '28','name_en' => 'KHAMYAB','name_dr' => 'خم آب','name_pa' => 'خم آب'],
            ['id' => '2807','province_id' => '28','name_en' => 'AQCHAH','name_dr' => 'آقچه','name_pa' => 'آقچه'],
            ['id' => '2808','province_id' => '28','name_en' => 'FAIZABAD','name_dr' => 'فیض آباد','name_pa' => 'فیض آباد'],
            ['id' => '2809','province_id' => '28','name_en' => 'MARDYAN','name_dr' => 'مردیان','name_pa' => 'مردیان'],
            ['id' => '2810','province_id' => '28','name_en' => 'QARQIN','name_dr' => 'قرقین','name_pa' => 'قرقین'],
            ['id' => '2811','province_id' => '28','name_en' => 'DARZAB','name_dr' => 'درز آب','name_pa' => 'درز آب'],
            ['id' => '2812','province_id' => '28','name_en' => 'PD 1 ','name_dr' => 'ناحیه 1 ','name_pa' => 'ناحیه 1 '],
            ['id' => '2813','province_id' => '28','name_en' => 'PD 2 ','name_dr' => 'ناحیه 2 ','name_pa' => 'ناحیه 2 '],
            ['id' => '2814','province_id' => '28','name_en' => 'PD 3 ','name_dr' => 'ناحیه 3 ','name_pa' => 'ناحیه 3 '],
            ['id' => '2815','province_id' => '28','name_en' => 'PD 4 ','name_dr' => 'ناحیه 4 ','name_pa' => 'ناحیه 4 '],
            ['id' => '2816','province_id' => '28','name_en' => 'Unknown ','name_dr' => 'نامعلوم ','name_pa' => 'نامعلوم '],
            ['id' => '2902','province_id' => '29','name_en' => 'PASHTUN KOT','name_dr' => 'پشتون کوت','name_pa' => 'پشتون کوت'],
            ['id' => '2903','province_id' => '29','name_en' => 'KHWAJA SABZ POSH-E-WALI','name_dr' => 'خواجه سبز پوش ولی','name_pa' => 'خواجه سبز پوش ولی'],
            ['id' => '2904','province_id' => '29','name_en' => 'ALMAR','name_dr' => 'المار','name_pa' => 'المار'],
            ['id' => '2905','province_id' => '29','name_en' => 'BIL CHIRAGH','name_dr' => 'بل چراغ','name_pa' => 'بل چراغ'],
            ['id' => '2906','province_id' => '29','name_en' => 'SHIRIN TAGAB','name_dr' => 'شرین تگاب','name_pa' => 'شرین تگاب'],
            ['id' => '2907','province_id' => '29','name_en' => 'QAISAR','name_dr' => 'قیصار','name_pa' => 'قیصار'],
            ['id' => '2908','province_id' => '29','name_en' => 'GURZIWAN','name_dr' => 'گرزیوان','name_pa' => 'گرزیوان'],
            ['id' => '2909','province_id' => '29','name_en' => 'DAWLAT ABAD','name_dr' => 'دولت آباد','name_pa' => 'دولت آباد'],
            ['id' => '2910','province_id' => '29','name_en' => 'KOHISTAN','name_dr' => 'کوهستان','name_pa' => 'کوهستان'],
            ['id' => '2911','province_id' => '29','name_en' => 'QARAM QOLE','name_dr' => 'قرمقول','name_pa' => 'قرمقول'],
            ['id' => '2912','province_id' => '29','name_en' => 'QURGHAN','name_dr' => 'قرغان','name_pa' => 'قرغان'],
            ['id' => '2913','province_id' => '29','name_en' => 'ANDKHOY','name_dr' => 'اندخوی','name_pa' => 'اندخوی'],
            ['id' => '2914','province_id' => '29','name_en' => 'KHAN CHARBAGH','name_dr' => 'خان چارباغ','name_pa' => 'خان چارباغ'],
            ['id' => '2915','province_id' => '29','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نا معلوم'],
            ['id' => '2916','province_id' => '29','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '2917','province_id' => '29','name_en' => 'PD 2','name_dr' => 'ناحیه 2','name_pa' => 'ناحیه 2'],
            ['id' => '2918','province_id' => '29','name_en' => 'PD 3','name_dr' => 'ناحیه 3','name_pa' => 'ناحیه 3'],
            ['id' => '2919','province_id' => '29','name_en' => 'PD 4','name_dr' => 'ناحیه 4','name_pa' => 'ناحیه 4'],
            ['id' => '2920','province_id' => '29','name_en' => 'PD 5','name_dr' => 'ناحیه 5','name_pa' => 'ناحیه 5'],
            ['id' => '2921','province_id' => '29','name_en' => 'PD 6','name_dr' => 'ناحیه 6','name_pa' => 'ناحیه 6'],
            ['id' => '2922','province_id' => '29','name_en' => 'PD 7','name_dr' => 'ناحیه 7','name_pa' => 'ناحیه 7'],
            ['id' => '2923','province_id' => '29','name_en' => 'PD 8','name_dr' => 'ناحیه 8','name_pa' => 'ناحیه 8'],
            ['id' => '2924','province_id' => '29','name_en' => 'PD 9','name_dr' => 'ناحیه 9','name_pa' => 'ناحیه 9'],
            ['id' => '2925','province_id' => '29','name_en' => 'PD 10','name_dr' => 'ناحیه 10','name_pa' => 'ناحیه 10'],
            ['id' => '2926','province_id' => '29','name_en' => ' (PROVINCIAL CAPITAL OF FARYAB) MAYMANA','name_dr' => '(مرکزولایت فاریاب) میمنه','name_pa' => '(مرکزولایت فاریاب) میمنه'],
            ['id' => '2927','province_id' => '29','name_en' => 'GHORMACH','name_dr' => 'غورماچ','name_pa' => 'غورماچ'],
            ['id' => '3001','province_id' => '30','name_en' => 'PROVINCIAL CAPITAL OF  HELMAND (LASHKARGAH)','name_dr' => '( مرکز ولایت هلمند) لشکرگاه','name_pa' => '( مرکز ولایت هلمند) لشکرگاه'],
            ['id' => '3002','province_id' => '30','name_en' => 'NAD ALI','name_dr' => 'نادعلی','name_pa' => 'نادعلی'],
            ['id' => '3003','province_id' => '30','name_en' => 'NAWA-I- BARIKZAYEE','name_dr' => 'نـاوه بـارکـزائـی','name_pa' => 'نـاوه بـارکـزائـی'],
            ['id' => '3004','province_id' => '30','name_en' => ' NAHER-I- SARAJ','name_dr' => 'نـهـر ســراج','name_pa' => 'نـهـر ســراج'],
            ['id' => '3005','province_id' => '30','name_en' => 'WASHER','name_dr' => 'واشـــیــر','name_pa' => 'واشـــیــر'],
            ['id' => '3006','province_id' => '30','name_en' => 'GARM SER','name_dr' => 'گرم سیر','name_pa' => 'گرم سیر'],
            ['id' => '3007','province_id' => '30','name_en' => 'NAWZAD','name_dr' => 'نوزاد','name_pa' => 'نوزاد'],
            ['id' => '3008','province_id' => '30','name_en' => 'SANGIN QALA','name_dr' => 'سنگـیــن قـلــعه','name_pa' => 'سنگـیــن قـلــعه'],
            ['id' => '3009','province_id' => '30','name_en' => 'MUSA QALA','name_dr' => 'مــوســی قـلــعـه','name_pa' => 'مــوســی قـلــعـه'],
            ['id' => '3010','province_id' => '30','name_en' => 'KAJAKI','name_dr' => 'کجکی','name_pa' => 'کجکی'],
            ['id' => '3011','province_id' => '30','name_en' => 'REG-E-KHAN NISHIN','name_dr' => 'ریـک خـانـشــیـن','name_pa' => 'ریـک خـانـشــیـن'],
            ['id' => '3012','province_id' => '30','name_en' => 'BAGHRAN','name_dr' => 'باغران','name_pa' => 'باغران'],
            ['id' => '3013','province_id' => '30','name_en' => 'DESHU','name_dr' => 'دیشو','name_pa' => 'دیشو'],
            ['id' => '3014','province_id' => '30','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '3015','province_id' => '30','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '3016','province_id' => '30','name_en' => 'PD 2','name_dr' => 'ناحیه 2','name_pa' => 'ناحیه 2'],
            ['id' => '3017','province_id' => '30','name_en' => 'PD 3','name_dr' => 'ناحیه 3','name_pa' => 'ناحیه 3'],
            ['id' => '3018','province_id' => '30','name_en' => 'PD 4','name_dr' => 'ناحیه 4','name_pa' => 'ناحیه 4'],
            ['id' => '3019','province_id' => '30','name_en' => 'Garashk','name_dr' => 'گرشک','name_pa' => 'گرشک'],
            ['id' => '3020','province_id' => '30','name_en' => 'Maarja','name_dr' => 'مارجه','name_pa' => 'مارجه'],
            ['id' => '3101','province_id' => '31','name_en' => 'PROVINCIAL CAPITAL OF  BADGHIS ( QALA-E-NOW )','name_dr' => '( مرکز ولایت بادغیس) قلعه نو','name_pa' => '( مرکز ولایت بادغیس) قلعه نو'],
            ['id' => '3102','province_id' => '31','name_en' => 'AB KAMARI','name_dr' => 'آبکمــری','name_pa' => 'آبکمــری'],
            ['id' => '3103','province_id' => '31','name_en' => 'MUQUR','name_dr' => 'مقـــر','name_pa' => 'مقـــر'],
            ['id' => '3104','province_id' => '31','name_en' => 'QADIS','name_dr' => 'قادس','name_pa' => 'قادس'],
            ['id' => '3105','province_id' => '31','name_en' => 'BALA MURGHAB','name_dr' => 'بالامــرغــاب','name_pa' => 'بالامــرغــاب'],
            ['id' => '3106','province_id' => '31','name_en' => 'JAWAND','name_dr' => 'جونـد','name_pa' => 'جونـد'],
            ['id' => '3107','province_id' => '31','name_en' => 'GHORMACH','name_dr' => 'غـورمــاچ','name_pa' => 'غـورمــاچ'],
            ['id' => '3108','province_id' => '31','name_en' => 'Unknown ','name_dr' => 'نامعلوم ','name_pa' => 'نامعلوم '],
            ['id' => '3202','province_id' => '32','name_en' => 'ENJIL','name_dr' => 'انجیل','name_pa' => 'انجیل'],
            ['id' => '3203','province_id' => '32','name_en' => 'NIZAM-E-SHAHID (GUZARA)','name_dr' => '(نظام شهید) گذره','name_pa' => '(نظام شهید) گذره'],
            ['id' => '3204','province_id' => '32','name_en' => 'KARRUKH','name_dr' => 'کرخ','name_pa' => 'کرخ'],
            ['id' => '3205','province_id' => '32','name_en' => 'ZENDAJAN','name_dr' => 'زنده جان','name_pa' => 'زنده جان'],
            ['id' => '3206','province_id' => '32','name_en' => 'PASHTUN ZARGHUN','name_dr' => 'پشتون زرغون','name_pa' => 'پشتون زرغون'],
            ['id' => '3207','province_id' => '32','name_en' => 'KUSHK (RUBAT-E-SANGI)','name_dr' => '(کشک) رباط سنگی','name_pa' => '(کشک) رباط سنگی'],
            ['id' => '3208','province_id' => '32','name_en' => 'GULRAN','name_dr' => 'گلران','name_pa' => 'گلران'],
            ['id' => '3209','province_id' => '32','name_en' => 'ADRASKAN','name_dr' => 'ادرسکن','name_pa' => 'ادرسکن'],
            ['id' => '3210','province_id' => '32','name_en' => 'KUSHK-E-KOHNA','name_dr' => 'کشک کهنه','name_pa' => 'کشک کهنه'],
            ['id' => '3211','province_id' => '32','name_en' => 'GHORYAN','name_dr' => 'غوریان','name_pa' => 'غوریان'],
            ['id' => '3212','province_id' => '32','name_en' => 'OBE','name_dr' => 'اوبه','name_pa' => 'اوبه'],
            ['id' => '3213','province_id' => '32','name_en' => 'KOHSAN','name_dr' => 'کهسان','name_pa' => 'کهسان'],
            ['id' => '3214','province_id' => '32','name_en' => 'SHINDAND','name_dr' => 'شیندند','name_pa' => 'شیندند'],
            ['id' => '3215','province_id' => '32','name_en' => 'FERSI','name_dr' => 'فرسی','name_pa' => 'فرسی'],
            ['id' => '3216','province_id' => '32','name_en' => 'CHISHT-E-SHARIF','name_dr' => 'چشت شریف','name_pa' => 'چشت شریف'],
            ['id' => '3217','province_id' => '32','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '3218','province_id' => '32','name_en' => 'PD 1','name_dr' => 'ناحیه1','name_pa' => 'ناحیه1'],
            ['id' => '3219','province_id' => '32','name_en' => 'PD 2','name_dr' => 'ناحیه2 ','name_pa' => 'ناحیه2 '],
            ['id' => '3220','province_id' => '32','name_en' => 'PD 3','name_dr' => 'ناحیه3','name_pa' => 'ناحیه3'],
            ['id' => '3221','province_id' => '32','name_en' => 'PD 4','name_dr' => 'ناحیه4','name_pa' => 'ناحیه4'],
            ['id' => '3222','province_id' => '32','name_en' => 'PD 5','name_dr' => 'ناحیه5','name_pa' => 'ناحیه5'],
            ['id' => '3223','province_id' => '32','name_en' => 'PD 6','name_dr' => 'ناحیه6','name_pa' => 'ناحیه6'],
            ['id' => '3224','province_id' => '32','name_en' => 'PD 7','name_dr' => 'ناحیه7','name_pa' => 'ناحیه7'],
            ['id' => '3225','province_id' => '32','name_en' => 'PD 8','name_dr' => 'ناحیه8','name_pa' => 'ناحیه8'],
            ['id' => '3226','province_id' => '32','name_en' => 'PD 9','name_dr' => 'ناحیه9','name_pa' => 'ناحیه9'],
            ['id' => '3227','province_id' => '32','name_en' => 'PD 10','name_dr' => 'ناحیه10','name_pa' => 'ناحیه10'],
            ['id' => '3228','province_id' => '32','name_en' => 'PD 11','name_dr' => 'ناحیه11','name_pa' => 'ناحیه11'],
            ['id' => '3229','province_id' => '32','name_en' => 'PD 12','name_dr' => 'ناحیه12','name_pa' => 'ناحیه12'],
            ['id' => '3230','province_id' => '32','name_en' => 'PD 13','name_dr' => 'ناحیه13','name_pa' => 'ناحیه13'],
            ['id' => '3231','province_id' => '32','name_en' => 'Provincial capital of Herat) Herat) ','name_dr' => '(مرکز ولایت هرات) هرات','name_pa' => '(مرکز ولایت هرات) هرات'],
            ['id' => '3301','province_id' => '33','name_en' => 'PROVINCIAL CAPITAL OF  FARAH (FARAH)','name_dr' => '( مرکز ولایت فراه) فراه','name_pa' => '( مرکز ولایت فراه) فراه'],
            ['id' => '3302','province_id' => '33','name_en' => 'PUSHTRUD','name_dr' => 'پشت رود','name_pa' => 'پشت رود'],
            ['id' => '3303','province_id' => '33','name_en' => 'KHAK-E-SAFED','name_dr' => 'خاک سفید','name_pa' => 'خاک سفید'],
            ['id' => '3304','province_id' => '33','name_en' => 'QALA-E-KAH','name_dr' => 'قلعه کاه','name_pa' => 'قلعه کاه'],
            ['id' => '3305','province_id' => '33','name_en' => 'SHIB KOH','name_dr' => 'شیب کوه','name_pa' => 'شیب کوه'],
            ['id' => '3306','province_id' => '33','name_en' => 'BALA BULUK','name_dr' => 'بالا بلوک','name_pa' => 'بالا بلوک'],
            ['id' => '3307','province_id' => '33','name_en' => 'ANAR DARA','name_dr' => 'اناردره','name_pa' => 'اناردره'],
            ['id' => '3308','province_id' => '33','name_en' => 'BAKWA','name_dr' => 'بکواه','name_pa' => 'بکواه'],
            ['id' => '3309','province_id' => '33','name_en' => 'LASH-E-JUWAYN','name_dr' => 'لاش جوین','name_pa' => 'لاش جوین'],
            ['id' => '3310','province_id' => '33','name_en' => 'GULISTAN','name_dr' => 'گلستان','name_pa' => 'گلستان'],
            ['id' => '3311','province_id' => '33','name_en' => 'PUR CHAMAN','name_dr' => 'پرچمن','name_pa' => 'پرچمن'],
            ['id' => '3312','province_id' => '33','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '3313','province_id' => '33','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '3314','province_id' => '33','name_en' => 'PD 2','name_dr' => 'ناحیه 2','name_pa' => 'ناحیه 2'],
            ['id' => '3315','province_id' => '33','name_en' => 'PD 3','name_dr' => 'ناحیه 3','name_pa' => 'ناحیه 3'],
            ['id' => '3316','province_id' => '33','name_en' => 'PD 4','name_dr' => 'ناحیه 4','name_pa' => 'ناحیه 4'],
            ['id' => '3317','province_id' => '33','name_en' => '---','name_dr' => '---','name_pa' => '---'],
            ['id' => '3401','province_id' => '34','name_en' => 'PROVINCIAL CAPITAL OF  NIMROZ (ZARANJ)','name_dr' => '( مرکز ولایت نیمروز) زرنج','name_pa' => '( مرکز ولایت نیمروز) زرنج'],
            ['id' => '3402','province_id' => '34','name_en' => 'KANG','name_dr' => 'کنگ','name_pa' => 'کنگ'],
            ['id' => '3403','province_id' => '34','name_en' => 'ASL-E-CHAKHANSUR','name_dr' => 'اصل چخانسور','name_pa' => 'اصل چخانسور'],
            ['id' => '3404','province_id' => '34','name_en' => 'CHAR BURJAK','name_dr' => 'چهاربرجک','name_pa' => 'چهاربرجک'],
            ['id' => '3405','province_id' => '34','name_en' => 'KHASHROD','name_dr' => 'خاشرود','name_pa' => 'خاشرود'],
            ['id' => '3406','province_id' => '34','name_en' => 'Unknown','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '3407','province_id' => '34','name_en' => 'PD 1','name_dr' => 'ناحیه 1','name_pa' => 'ناحیه 1'],
            ['id' => '3408','province_id' => '34','name_en' => 'Delaram','name_dr' => 'دلارام ','name_pa' => ''],
            ['id' => '3501','province_id' => '35','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '3502','province_id' => '35','name_en' => 'UNKNOWN','name_dr' => 'نامعلوم','name_pa' => 'نامعلوم'],
            ['id' => '3503','province_id' => '26','name_en' => 'Shahrak Safa ','name_dr' => 'شهرصفاء (نرنگ و جلدک)','name_pa' => 'شهرصفاء (نرنگ و جلدک)'],
            ['id' => '3504','province_id' => '6','name_en' => 'Haska Meena','name_dr' => 'هسکه مینه ','name_pa' => 'هسکه مینه '],
            ['id' => '3505','province_id' => '7','name_en' => 'Laghman University ','name_dr' => 'پوهنتون لغمان','name_pa' => 'پوهنتون لغمان'],
            ['id' => '3506','province_id' => '16','name_en' => 'Pargmatal','name_dr' => 'برګمتال','name_pa' => 'برګمتال'],
            ['id' => '3507','province_id' => '17','name_en' => 'TESHGAN','name_dr' => 'تیشگان','name_pa' => 'تیشگان'],
            ['id' => '3508','province_id' => '10','name_en' => 'BATOO','name_dr' => 'باتو','name_pa' => 'باتو'],
            ['id' => '3509','province_id' => '23','name_en' => 'FEROZ KHOH','name_dr' => 'فیروز کوه','name_pa' => 'فیروز کوه'],
            ['id' => '3510','province_id' => '8','name_en' => 'ABSHAR','name_dr' => 'آبشار','name_pa' => 'آبشار'],
            ['id' => '3511','province_id' => '27','name_en' => 'TAKHTA PUL','name_dr' => 'تخته پل','name_pa' => 'تخته پل'],
            ['id' => '3512','province_id' => '25','name_en' => 'CHENARTO','name_dr' => 'چنارتو','name_pa' => 'چنارتو'],
            ['id' => '3513','province_id' => '25','name_en' => 'GAZAAB','name_dr' => 'گزاب','name_pa' => 'گزاب'],
            ['id' => '3514','province_id' => '13','name_en' => 'GERDA KHEBRI','name_dr' => 'گرده خبری','name_pa' => 'گرده خبری'],
            ['id' => '3515','province_id' => '13','name_en' => 'MEERZAKA','name_dr' => 'میرزکه','name_pa' => 'میرزکه'],
            ['id' => '3516','province_id' => '3','name_en' => 'GUL BAHAR','name_dr' => 'گلبهار','name_pa' => 'گلبهار'],
            ['id' => '3517','province_id' => '24','name_en' => 'PATO','name_dr' => 'پاتو','name_pa' => 'پاتو'],
            ['id' => '3518','province_id' => '24','name_en' => 'NAWA MISH','name_dr' => 'ناوه میش','name_pa' => 'ناوه میش'],
            ['id' => '3519','province_id' => '19','name_en' => 'GUL TAPA (MOWAQAT)','name_dr' => 'ګل تپه (موقت)','name_pa' => 'ګل تپه (موقت)'],
            ['id' => '3520','province_id' => '19','name_en' => 'KALBAAD','name_dr' => 'کلباد','name_pa' => 'کلباد'],
            ['id' => '3521','province_id' => '19','name_en' => 'AAQTASH (MOWAQAT)','name_dr' => 'آقتاش (موقت)','name_pa' => 'آقتاش (موقت)'],
            ['id' => '3522','province_id' => '4','name_en' => 'HESE DOWM BEHSOOD','name_dr' => 'حصه دوم بهسود','name_pa' => 'حصه دوم بهسود'],
            ['id' => '3523','province_id' => '32','name_en' => 'PUSHT KOH','name_dr' => 'پشت کوه','name_pa' => 'پشت کوه']
          ];
          
        foreach($districts as $district){

            District::create($district);
        }

    }
}
