import {
    Alignment,
    Autoformat,
    AutoImage,
    Base64UploadAdapter,
    BlockQuote,
    Bold,
    ClassicEditor,
    Code,
    CodeBlock,
    Essentials,
    FindAndReplace,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    GeneralHtmlSupport,
    Heading,
    Highlight,
    HorizontalLine,
    Image,
    ImageCaption,
    ImageInsert,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Indent,
    IndentBlock,
    Italic,
    Link,
    List,
    ListProperties,
    MediaEmbed,
    Paragraph,
    PasteFromOffice,
    RemoveFormat,
    SelectAll,
    SourceEditing,
    Strikethrough,
    Subscript,
    Superscript,
    Table,
    TableCaption,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    TextTransformation,
    TodoList,
    Underline,
    Undo,
} from 'ckeditor5';

export const laboratoryCkEditorPlugins = [
    Essentials,
    Paragraph,
    Heading,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Subscript,
    Superscript,
    Code,
    Link,
    List,
    ListProperties,
    TodoList,
    Indent,
    IndentBlock,
    BlockQuote,
    Table,
    TableToolbar,
    TableProperties,
    TableCellProperties,
    TableColumnResize,
    TableCaption,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    ImageInsert,
    ImageResize,
    AutoImage,
    Base64UploadAdapter,
    MediaEmbed,
    Alignment,
    FontSize,
    FontFamily,
    FontColor,
    FontBackgroundColor,
    Highlight,
    HorizontalLine,
    CodeBlock,
    SourceEditing,
    GeneralHtmlSupport,
    PasteFromOffice,
    Autoformat,
    TextTransformation,
    RemoveFormat,
    SelectAll,
    FindAndReplace,
    Undo,
];

export const laboratoryCkEditorToolbar = [
    'undo',
    'redo',
    '|',
    'sourceEditing',
    'findAndReplace',
    'selectAll',
    '|',
    'heading',
    '|',
    'fontSize',
    'fontFamily',
    'fontColor',
    'fontBackgroundColor',
    '|',
    'bold',
    'italic',
    'underline',
    'strikethrough',
    'subscript',
    'superscript',
    'code',
    'removeFormat',
    '|',
    'highlight',
    'link',
    'insertImage',
    'mediaEmbed',
    'insertTable',
    'horizontalLine',
    'blockQuote',
    'codeBlock',
    '|',
    'alignment',
    '|',
    'bulletedList',
    'numberedList',
    'todoList',
    '|',
    'outdent',
    'indent',
];

export const laboratoryCkEditorConfig = {
    licenseKey: 'GPL',
    plugins: laboratoryCkEditorPlugins,
    toolbar: {
        items: laboratoryCkEditorToolbar,
        shouldNotGroupWhenFull: true,
    },
    heading: {
        options: [
            { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
            { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
            { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
            { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
            { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
        ],
    },
    fontSize: {
        options: [10, 12, 14, 'default', 18, 20, 24, 28, 32],
        supportAllValues: true,
    },
    fontFamily: {
        supportAllValues: true,
    },
    image: {
        toolbar: [
            'imageTextAlternative',
            'toggleImageCaption',
            '|',
            'imageStyle:inline',
            'imageStyle:block',
            'imageStyle:side',
            '|',
            'resizeImage',
        ],
        resizeOptions: [
            { name: 'resizeImage:original', label: 'Original', value: null },
            { name: 'resizeImage:25', label: '25%', value: '25' },
            { name: 'resizeImage:50', label: '50%', value: '50' },
            { name: 'resizeImage:75', label: '75%', value: '75' },
        ],
    },
    table: {
        contentToolbar: [
            'tableColumn',
            'tableRow',
            'mergeTableCells',
            'tableProperties',
            'tableCellProperties',
            'tableColumnResize',
        ],
    },
    link: {
        decorators: {
            openInNewTab: {
                mode: 'manual',
                label: 'Open in a new tab',
                attributes: {
                    target: '_blank',
                    rel: 'noopener noreferrer',
                },
            },
        },
    },
    htmlSupport: {
        allow: [
            {
                name: /.*/,
                attributes: true,
                classes: true,
                styles: true,
            },
        ],
    },
};

export { ClassicEditor };
